spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/study"
    database: "study"
    user: "root"
    password: "pass5678"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        dialect = org.hibernate.dialect.MySQL5InnoDBDialect


upload-config:
  max-file-size: "5Mb"
  max-upload-times: 4